// Auto-regenerated by GameVersionPreBuildProcessor before every build. Manual edits will be overwritten.
namespace Code.Common.Utilities
{
	public static class GameVersion
	{
		public const int iOS_BuildNumber_int = 1;
		public const int Android_BuildNumber_int = 1;
	}
}
