using System.IO;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

namespace Code.Infrastructure.BuildPreprocessors.Editor
{
	public class GameVersionPreBuildProcessor : IPreprocessBuildWithReport
	{
		private const string VersionFileRelativePath = "Code/Common/Utilities/GameVersion.cs";

		public int callbackOrder => 0;

		public void OnPreprocessBuild(BuildReport report)
		{
			WriteVersion();
		}

		[MenuItem("Game/Update GameVersion", false, 0)]
		private static void WriteVersion()
		{
			string finalPath = Path.Combine(Application.dataPath, VersionFileRelativePath);

			if (File.Exists(finalPath) == false)
				File.CreateText(finalPath).Dispose();

			int.TryParse(PlayerSettings.iOS.buildNumber, out int iosBuildNumber);
			int androidBuildNumber = PlayerSettings.Android.bundleVersionCode;

			string newText = "// Auto-regenerated by GameVersionPreBuildProcessor before every build. " +
				"Manual edits will be overwritten.\r\n" +
				"namespace Code.Common.Utilities\r\n" +
				"{\r\n" +
				"\tpublic static class GameVersion\r\n" +
				"\t{\r\n" +
				FormatVariable(name: "iOS_BuildNumber_int", value: iosBuildNumber) +
				FormatVariable(name: "Android_BuildNumber_int", value: androidBuildNumber) +
				"\t}\r\n" +
				"}\r\n";

			string currentText = File.ReadAllText(finalPath);

			if (currentText == newText)
				return;

			Debug.Log("Updated GameVersion.cs");
			File.WriteAllText(finalPath, newText);
			AssetDatabase.Refresh();
		}

		private static string FormatVariable(string name, int value) =>
			$"\t\tpublic const int {name} = {value};\r\n";
	}
}
